### ISSUE TITLE
Resilient slug usage

### ISSUE THREAD

**Issue by hirusi** [grantcodes/postr#62]
At the moment, a [slug is assumed to be necessary and used as-is by Postr](https://github.com/grantcodes/postr/blob/master/lib/get-permalink-from-mf2.js#L27).

For [better spec compliance](https://indieweb.org/Micropub-extensions#Slug) (see quote at the end of this issue) and resilience, it would be lovely if we:

- Slugify the provided slug, assuming the user can sometimes not write a proper slug. Maybe an accidental space instead of a dash separator.
- Check for conflicts, and if any, modify the slug -- could be as simple as adding an index number after the slug with a separator. A `hello-world` slug when received for a second time causes it to change to `hello-world-1`.
- If a slug field is sent, but is empty, generate a random string of a defined character size.

[Indiekit](https://github.com/getindiekit/indiekit/) takes this route if you're interested in [taking a look at the source.](https://github.com/getindiekit/indiekit/blob/main/packages/endpoint-micropub/lib/microformats.js#L199)

> The server may or may not decide to respect the requested slug, based on whether it would cause conflicts with other URLs on the site. For example, some URL structures are {year}/{slug}, so the server may decide to modify the slug to avoid conflicting with an existing one.

**Comment by grantcodes** [comment]
I think it already does this?

- It generates a default slug based on post properties (like name) or the date in the [`set-defaults` middleware](https://github.com/grantcodes/postr/blob/master/lib/db-middleware/set-defaults.js) .
- Conflicts are handled by the [`fix-permalink-conflicts` middleware](https://github.com/grantcodes/postr/blob/master/lib/db-middleware/fix-permalink-conflicts.js)
- I don't think it formats the `mp-slug` property if it is supplied in the micropub request. I think I assumed it is still possible to have things like capital letters and spaces in your slugs. Though maybe it should be sanitized just to keep things easier.

**Comment by hirusi** [comment]
> I think it already does this?

I only had a cursory look. You're most likely right! 🙂

 I'll set up a local app and test Postr out. If I'm not wrong, it does support writing to a GitHub repo (for a static site workflow)?

**Comment by grantcodes** [comment]
It does not support commiting to a repo at the moment. By default it uses a database stored on the local filesystem. But the [database storage system can be swapped out,](https://github.com/Level/awesome#stores) so there may be a GitHub or flat files as a DB option but I doubt it. 

I run it as a service and query it when running a build.
